### ISSUE TITLE
Confused while migrating to the new charts

### ISSUE THREAD

**Issue by dkulchinsky** [OpenUnison/helm-charts#30]
Hey @mlbiam 👋🏼 

We're currently using the openunison-operator and the now-deprecated `openunison-k8s-login-oidc` charts to deploy Orchestra.

I started looking into migrating to the new charts, following the docs https://openunison.github.io/upgrading/ it appears we will need to use 3 charts:

- openunison-operator
- orchestra
- orchestra-login-portal

but I'm somewhat confused on some bits:
1. `orchestra` chart's values file is missing the `oidc` section, I found a reference in the docs (https://openunison.github.io/deployauth/#openid-connect) however these values are not actually being referred to in any of the templates (except in some if clauses), in the `openunison-k8s-login-oidc` chart these were mapped to environment variables which no longer exist in the new chart? 

do I need to add these manually into `openunison.non_secret_data`?

2. the operator previously created all the resource (deployment, ingress, etc..) which now are created with regular manifests from the `orchestra` chart, however the openunison custom resource (in openunison.yaml template) still defines ingress, deployment and other bits. Is there some duplication here? what is the operator responsible for now? i.e. which resource will be generated by the operator what is deployed by the chart?

3. I'm also struggling to understand the role of `orchestra-login-portal` chart and from the values it looks like it's duplicating the values from `orchestra` chart?

**Comment by mlbiam** [comment]
Great questions, we should add these answers to the docs.

> orchestra chart's values file is missing the oidc section, I found a reference in the docs

Correct, to maintain backwards compatibility with the values from the old repos we decided to not move the different auth methods into their own section or require any kind of explicit flag such as `useAuth=oidc`.  The `orchestra-login-portal` charts look to see if a section is present, and if it is creates the appropriate configurations.  To make sure users don't specify multiple options (ie you can't specify both `activedirectory` and `oidc`), there's a test that runs prior to deploying `orchestra-login-portal` to make sure you only specify one authentication configuration block.

> do I need to add these manually into openunison.non_secret_data?

what are you referring to by *these*?

> the operator previously created all the resource (deployment, ingress, etc..) which now are created with regular manifests from the orchestra chart, however the openunison custom resource (in openunison.yaml template) still defines ingress, deployment and other bits. Is there some duplication here? what is the operator responsible for now? i.e. which resource will be generated by the operator what is deployed by the chart?

The operator is primarily responsible for:
1.  Creating the `Secret` used by openunison that contains the keystores and configuration options.
2. Creating the validating webhook and its corresponding k8s configuration (more on that further down)
3. Rolling out new versions of the `Deployment` when an update is made
4. Deploying ActiveMQ when openunison is used for Namespace as a Service

On a side note, we're in the process of eliminating the operator.  Hoping by 2023 we'll move everything the operator does out of a stand alone operator and into a combination of the orchestra chart and init containers for the pods.  In addition to having one less thing to deploy, it will make it easier for us to integrate directly with key vaults for secret data.

>
> I'm also struggling to understand the role of orchestra-login-portal chart and from the values it looks like it's duplicating the values from orchestra chart?

The values look duplicated because we wanted to keep things as simple as we could, so we wanted you to be able to use the same values.yaml across both charts (for the reason explained below).

Starting with 1.0.24, OpenUnison began supporting a k8s-native approach to configuration making the config custom resources instead of embedding them in the container.  This makes it much easier to customize.  For instance if you want to use your own logos you can do that now without rebuilding the container.  The major downside to this approach is that in order to ensure that we are validating objects as they're created, we needed an admission webhook.  

We both wanted to validate that certain resources are available at setup as well as to validate objects that are too complex to be described by the json schema language used by CRs, so we built a validation webhook into openunison.  The issue we ran into though was helm isn't "smart" enough to do proper sequencing and ordering.  We couldn't tell Helm to wait for openunison to be running before creating all the configuration objects, and so the deployment would fail.  We had to break up the deployment of the openunison container from the deployment of the configuration.

We also broke out the creation of the "infrastructure" for openunison from the operator.  We found that making updates to k8s native objects was too painful and wasn't proper to do in an operator (https://twitter.com/mlbiam/status/1451562996036157461).  It made sence in 2018 when we first created it, but today it's counter productive.  Moving the k8s native objects into the `orchestra` chart gives us the ability to better integrate multiple scenarios, like quickly being able to switch between nginx and istio (and eventually traefik).  And on the NaaS side, switch between DBs instead of just MySQL.



So the responsibilities are:

| Chart | Responsibilities |
| ----- | ---------------- |
| openunison | Deploys the CRDs and the operator |
| orchestra | Deploys the *infrastructure* for openunison (`Ingress`, `Deployments`, etc) |
| orchestra-login-portal | Application level configurations for openunison (how to authenticate, trusts, etc) |

**Comment by dkulchinsky** [comment]
Hey @mlbiam 👋🏼 

Appreciate your thorough response! I think I understand things somewhat more clearly now.

The complexity is however in understand the nuances of these charts is quite high, I'll be working on transitioning over in our sandbox cluster and will reach out if I hit any issues.

one thing I noticed and wanted to confirm:

one question: the OIDC client_id used to be supplied via the orchestra-secret-source and looks like it's now a Chart value parameter, can we still provide it via the secret with the new charts? (we mutate this into said secret from Vault and would like to keep things as-is if possible)

**Comment by mlbiam** [comment]
> The complexity is however in understand the nuances of these charts is quite high, I'll be working on transitioning over in our sandbox cluster and will reach out if I hit any issues.

understand 100%.  we do our best to balance a potentially unique approach to deployment, doing so in a way that is consistent with more defacto standards (like helm), and dealing with the inconsistencies of k8s in general (ie k8s is eventually consistent but helm doesn't appreciate that).  There are workflow tools for more complex deployment mechanisms but they're not standard and we don't want to force any of them.

Please, keep the feedback coming so we can make it easier!

>  one question: the OIDC client_id used to be supplied via the orchestra-secret-source and looks like it's now a Chart value parameter, can we still provide it via the secret with the new charts? (we mutate this into said secret from Vault and would like to keep things as-is if possible)

Since we moved to helm it's always been in the values.yaml.  What's changed is that we don't require all parameters to be in the `orchestra` OpenUnison object anymore, so client_id gets embedded directly into the resulting authchain object.  `client_id` isn't generally considered sensitive, but I could see why you'd want to keep it that way.  

I'm assuming you're syncing from vault into a `Secret` using something like the csi secret store?  We can add a flag that pull the `client_id` directly from the `orchestra-secrets-source` instead of out of the values.yaml.

**Comment by mlbiam** [comment]
@dkulchinsky added the option to make chart pull the clientid from the secret.  See https://openunison.github.io/deployauth/#openid-connect

**Comment by mlbiam** [comment]
@dkulchinsky - this has been open for a while.  Have you been able to migrate?
